version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: unless-stopped
    networks:
      - shared-net

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - shared-net

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: reddit
      POSTGRES_PASSWORD: reddit
      POSTGRES_DB: reddit_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shared-net

  celery_worker:
    build:
      context: .
      dockerfile: docker/pipeline.Dockerfile
    container_name: celery_worker
    depends_on:
      - rabbitmq
      - metrics_server
      - postgres
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672/
      - C_FORCE_ROOT=true
    command: celery -A app.celery_app worker --loglevel=info
    env_file:
      - auth.env
      - postgres.env
      - reddit.env
    networks:
      - shared-net

  celery_beat:
    build:
      context: .
      dockerfile: docker/pipeline.Dockerfile
    container_name: celery_beat
    depends_on:
      - rabbitmq
      - metrics_server
      - postgres
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672/
      - C_FORCE_ROOT=true
    command: celery -A app.celery_app beat --loglevel=info
    env_file:
      - auth.env
      - postgres.env
      - reddit.env
    networks:
      - shared-net

  metrics_server:
    build:
      context: .
      dockerfile: docker/metrics.Dockerfile
    container_name: metrics_server
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      - PROMETHEUS_METRICS=true
    networks:
      - shared-net

  flower:
    image: mher/flower
    container_name: flower
    command: celery --broker=amqp://user:password@rabbitmq:5672/ flower
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
    networks:
      - shared-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - shared-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - shared-net



volumes:
  grafana-storage:
  postgres_data:

networks:
  shared-net:
    name: shared-net
    external: true
